#!/usr/bin/env python
#-*- coding: utf-8 -*-

a = ("1", "2", "3", "4")

def recursion(abcd):
    b = list(map(lambda x: "{" + x, a)) + list("}" * len(a))
    return (''.join(b))

def main():
    print(recursion(a))

if __name__ == '__main__':
    main()
